apiVersion: v1
kind: Service
metadata:
  annotations:
    qingyuanos.io/catalog-by: '{"version": "v1alpha", "lib": "https://github.com/qingyuancloud/harpoon", "module": "https://github.com/gogits/gogs"}'
  labels:
    app: gogs
    heritage: qingyuancloud.com
    name: gogs
    project: gogs.io
  name: gogs
  # namespace: harpoon
spec:
  ports:
  - name: gogs-wui
    nodePort: 32130  # Optional, or Kubernetes generate a random port if not customized
    port: 3000
    protocol: TCP
  - name: gogs-ssh
    nodePort: 32129  # Optional, or Kubernetes generate a random port if not customized
    port: 22
    protocol: TCP
  selector:
    name: gogs
  type: NodePort
